modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "ranchersdelight" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Rancher's Delight" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# logoFile="examplemod.png" #optional
credits = "My wonderful Wife"
authors = "EpicSquid & EmOcean"
description = '''
A mod to add more ranching to Minecraft, adding new ways of obtaining items from various animals without having to kill
them.
'''
[[dependencies.ranchersdelight]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ranchersdelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ranchersdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.18.2-1.1.0)"
ordering = "AFTER"
side = "BOTH"
